apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: rhcos4-stig
  namespace: openshift-compliance
profiles:
- apiGroup: compliance.openshift.io/v1alpha1
  kind: Profile
  name: rhcos4-stig
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: default
---
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: rhcos4-stig
  namespace: openshift-compliance
status:
  phase: DONE
